### PR TITLE
Update roadmap: AlmaLinux now available on DigitalOcean

### PR DESCRIPTION
**Pull request by renich**
Just update the roadmap.

The link to it is till missing. Will add it when available.

### CODE REVIEW

**Review by srbala — APPROVED** [review]
LGTM.

PR Can be merged when AlmaLinux is available in DO marketplace

**Comment by srbala** [comment]
@LKHN is `DC` approved AlmaLinux images? this this PR ready for merge?

**Comment by LKHN** [comment]
> @LKHN is `DC` approved AlmaLinux images? this this PR ready for merge?

The PR https://github.com/digitalocean/marketplace-partners/commit/c7dced432db5c03527e49aff11d0a71445fbcff9  is merged but not available on the WEBUI yet:

**Comment by LKHN** [comment]
image

**Comment by srbala** [comment]
@LKHN @renich we might need two more PRs for Almalinux to showup on web UI. https://github.com/search?q=org%3Adigitalocean+rocky&type=issues

**Comment by LKHN** [comment]
> @LKHN @renich we might need two more PRs for Almalinux to showup on web UI. https://github.com/search?q=org%3Adigitalocean+rocky&type=issues

Good catch @srbala , Thanks!
PRs are ready:
https://github.com/digitalocean/droplet-1-clicks/pull/45
https://github.com/digitalocean/droplet-agent/pull/32

**Comment by srbala** [comment]
@LKHN Thank you
@ccallahan Please review and approve new PRs

**Comment by caquillo07** [comment]
👋🏼  @LKHN  @srbala sorry for the delay on responding.

Our internal teams are looking into adding support for AlmaLinux, but it's not in the immediate roadmap. We understand how popular and beneficial this OS is, so we are trying to figure out what the best approach is. 

The UI you are referring to above is not powered by the public repos we have, those are powered by internal tools. Those images need to be vetted, and prepped to run on top of the DigitalOcean infrastructure. I know you tried to submit the image through the Marketplace, and we were **really** hoping we could get it publish there at least, but there are technical limitations that won't allow us to get custom images published just yet. 

Those technical limitations were unknown to us at the Marketplace team until after we merged your last PR https://github.com/digitalocean/marketplace-partners/pull/143, so unfortunately I will be forced to revert those changes. 

Really sorry for any inconvenience or delays this may cause, but rest assure we are looking into it.
Thank you!

**Comment by srbala** [comment]
@caquillo07 Thanks for your input. Please let us know is there anyway our community team @AlmaLinux/cloud-sig can help

**Comment by srbala** [comment]
@LKHN has some enhancemnts/cleanup, do you think that might help? #30, #31, #32

**Comment by LKHN** [comment]
> @LKHN has some enhancemnts/cleanup, do you think that might help? #30, #31, #32

#30 and #31 ones  DO Image related, the submitted image already has these changes.
There's also a fresh image in our GH release section: https://github.com/AlmaLinux/cloud-images/releases/tag/digitalocean-20210810
Everyone can use the image with Images >> Custom Images >> Import from URL (the image file URL from releases)

**Comment by caquillo07** [comment]
@LKHN is correct, customers can use custom images right, my comment above was referring to us being able to distribute them through the Marketplace. The latter goes through some internal audits that make certain assumptions on images, if they are not present it fails, which is what happened in your case

**Comment by ccallahan** [comment]
Sorry about the delay, I've been sicker than a dog the past few days.

**Pull request merged**
