### PR TITLE
Add Vagrant VMWare provider for aarch64 support

### LINKED ISSUE #134: Add VMWare Fusion provider for Vagrant box, Almalinux 9 - aarch64
Original Issue in https://bugs.almalinux.org/view.php?id=361

This cross-reference issue for discussion/test/track

### PR DESCRIPTION
**Pull request by srbala**
This PR Request resolves #134

### CODE REVIEW

**Review by chissg — APPROVED** [review]
Not an expert on this by any means, but looks good to me. Many thanks for the quick turnaround!

**Comment by srbala** [comment]
@chissg Chris, thank you

**Comment by srbala** [comment]
@chissg I am able to build the box in headless mode. But, to run the box it's expecting both settings `v.gui = true` and `v.vmx["ethernet0.virtualdev"] = "vmxnet3"`. I am not sure if it is a bug with the packer-plugin or VMWare SDK.

Do you have support with VMWare, maybe they can advise.

**Comment by chissg** [comment]
I was encouraged by your change https://github.com/AlmaLinux/cloud-images/commit/d5288617240e3d132a7cb8a9107da01b39e98af5#diff-1d0d44efc45d605f3b8c3bd1f132aea1b189749300b324c5a6b8f01eed552473R170, is all. A brief search online suggests [the problem might be related to more recent guest kernels](https://github.com/hashicorp/vagrant/issues/12695#issuecomment-1114898461), but beyond that I have nothing.

**Comment by srbala** [comment]
Some of the Apple M1 kernel support issues within VMWare and parallel tools and vagrant boxes have been there for months

**Review by codyro — COMMENTED** [review]
👍

**Pull request merged**
