### PR TITLE
feat(9): updates for azure

### PR DESCRIPTION
**Pull request by LKHN**
- Remove depreciated ifcfg script method.
- Add new packages requested by community.
- Only generated udev rules for the PTP clock on AlmaLinux OS 8. Since the systemd version on the AlmaLinux OS 9 and newer have this patch already.
- Update the chrony configuration accordingly the recents changes from the Azure documentation.
- Exclude the qemu-guest-agent from the installation since it is not needed on the Hyper-V virtualization on Azure.

### CODE REVIEW

**Comment by codyro** [comment]
Is tuned usually disabled on cloud images? I thought it was already shipped & enabled in EL8/9.

**Comment by LKHN** [comment]
I think the service should enabled by default when you install it. I am going to double check it.

**Comment by LKHN** [comment]
>Is tuned usually disabled on cloud images?
I think it should be included due `virtual-guest` profile of TuneD. Maybe I should handle it on Azure as I did on Generic Cloud; Install, Enable service and make sure it is running with the correct profile.

https://github.com/AlmaLinux/cloud-images/blob/3d07647847acbadb0aae6b71020eb31a908e4cc8/ansible/roles/gencloud_guest/tasks/main.yml#L42-L70

**Comment by LKHN** [comment]
@codyro Checked.

The `tuned.service` is enabled by default. See: https://git.almalinux.org/rpms/almalinux-release/src/commit/dae39a14f7e327d2584c83d14a7a48fea21e84d2/90-default.preset#L114-L115

So just installing of the package is enough. Which is already included on the PR.

Seems like on the gencloud_guest Ansible role, I could not get enough with just an installation. :) (see my previous reply)

1. Start and enable the tuned.service.
2. Make sure the active profile is `virtual-guest`.
3. Verify if the current system settings match with the current profile (`virtual-guest`).

Not sure if I use it here too? What do you think?

**Comment by LKHN** [comment]
Since this PR has other changes and there is nothing to neither remove or change on its current state, going to merge it. We can continue to discuss it.

**Pull request merged**
