### PR TITLE
Update almalinux-9-gencloud.pkr.hcl | fix, ansible error - extra arguments at end of line

### PR DESCRIPTION
**Pull request by maksimsamt**
Ansible error, example:
```
almalinux-9-gencloud-bios-x86_64: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"127.0.0.1\". Make sure this host can be reached over ssh: command-line line 0: keyword controlmaster extra arguments at end of line\r\n", "unreachable": true}
```

### CODE REVIEW

**Comment by LKHN** [comment]
Only AlmaLinux OS 9 or OpenSSH >= 9.0 understand this flag. I have to put it another branch https://github.com/AlmaLinux/cloud-images/tree/scp_90
`--scp-extra-args -O`

**Comment by LKHN** [comment]
Thanks!
I need to test it in Fedora 39 and AlmaLinux OS 9. If it works then will move to `scp_90` branch. which is intended for modern systems.

**Comment by LKHN** [comment]
@maksimsamt Thanks a lot for bringing attention!

Closing it in favour of #176 which covers all image types.

**Comment by maksimsamt** [comment]
Can confirm that https://github.com/AlmaLinux/cloud-images/pull/176 changes and accordingly build process now correctly works on Fedora 40

**Comment by LKHN** [comment]
@maksimsamt Thanks a lot for confirming. I also tested other distros to make sure everyone can build images.

https://github.com/AlmaLinux/cloud-images/issues/172#issuecomment-2120971112

**Pull request closed without merging**
