### PR TITLE
Add DigitalOcean build

### PR DESCRIPTION
**Pull request by renich**
This is the implementation of what was recommended by DigitalOcean at
https://github.com/digitalocean/marketplace-partners in order to build
an image that passes all tests.

The instructions to run it are as follows:

* setup doctl first (api auth and all)
* run `bin/digitalocean-import_latest_image.bash`
* export `DIGITALOCEAN_TOKEN`
* run the build.

### CODE REVIEW

**Comment by srbala** [comment]
Since scirpts under vm-scripts specific to Got a few on last Christmas sale use, may be vm-digitalocean or vm-scripts-digitalocean
Some typos in Readme.md
Is the scripts run automatically or called from another scirpt, you may want expand your Readme.md for it. Good documentation, less question from end users.
Not sure community team has access/sponsor from digitalocean for test environment. Team members can speakup for it.

**Comment by renich** [comment]
OK, I've corrected all of it. Maybe just a review of the main README.md file?

**Review by srbala — APPROVED** [review]
LGTM

**Comment by srbala** [comment]
PR Looks good, Sig team I'll wait for your feedback, if no objections I'll merge tonight

**Comment by srbala** [comment]
Replacing with PR#25

**Pull request closed without merging**
